### PR TITLE
Don't say Ricochet hasn't been audited

### PR DESCRIPTION
**Pull request by NinebitX**
It has now been over a year since the NCC Group audit:
* https://motherboard.vice.com/en_us/article/ricochet-encrypted-messenger-tackles-metadata-problem-head-on
* https://ricochet.im/files/ricochet-ncc-audit-2016-01.pdf

### CODE REVIEW

**Comment by Rspigler** [comment]
I agree with @NinebitX 

We could also post an "Audit Results" section on the website, listing the vulnerabilities that were found, while maintaining the noob friendly vulnerability (Critical, High, Medium, Low, Informational) and categorical breakdown (Cryptography, Data Exposure, Data Validation) that the NCCGroup did.

Each vulnerability could then point to the merged pull request that fixed those vulnerabilities (some lower risk 'vulnerabilities' found are still WIP I believe - these could be explained and pointed to the pull request working on them)

**Comment by special** [comment]
@Rspigler that would be neat -- the [wiki](https://github.com/ricochet-im/ricochet/wiki) would be a good place

**Comment by Rspigler** [comment]
@special You got it - I'll do my best but it'll need review most likely

**Comment by Rspigler** [comment]
The WIP Summary is posted here: (https://github.com/ricochet-im/ricochet/wiki/NCC-Audit-Results-%5BWIP%5D)

Some of the vulnerabilities I was unable to find PRs or Open Issues for, so please check/fill out for me wherever I have made mistakes.

As new releases come out, efforts should be made to keep this wiki article up to date - I of course will try my best to do so.

**Pull request merged**
