### PR TITLE
Add a nice screenshot to the README.md

### PR DESCRIPTION
**Pull request by gnujedi**
I created a fictional conversation on Ricochet. People want to see what the app looks like. Image under creative commons zero public domain tool. This could get added to the main ricochet.im website as well.

### CODE REVIEW

**Comment by taoeffect** [comment]
cool, i like it. :)

**Comment by Hakarin** [comment]
Looks good

**Comment by sts10** [comment]
Very smart. 

Don't know if this would be too much, but if you sent me a screen recording of you "having" the conversation I'd be happy to make a GIF of it either for the README and/or [the Ricochet website](https://github.com/ricochet-im/website). It's easy to take a screen recording on OS X with Quicktime (`File > New Screen recording...`).

**Comment by taoeffect** [comment]
Another PR can always add a GIF.

**Comment by sts10** [comment]
Yep, for sure. In favor of getting this one through first then getting GIF-y later if we like.

**Pull request merged**
